### ISSUE TITLE
uploading images fails

### ISSUE THREAD

**Issue by laaber** [fmenabe/python-dokuwiki#7]
Hi,

I'm using python-dokuwiki 0.4.0-5-gfc55e58 with dokuwiki 2016-06-26a "Elenor of Tsort".
When uploading image files (png, jpg) I get this error message, no matter if I run wiki.medias.set or wiki.medias.add:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dokuwiki.py", line 362, in add
    Binary(fhandler.read()), ow=overwrite)
  File "/usr/local/lib/python2.7/dist-packages/dokuwiki.py", line 113, in send
    raise DokuWikiError(err)
dokuwiki.DokuWikiError: <Fault 1: 'The uploaded content did not match the .png file extension.'>
```

PDF files work fine and I can upload images from the web interface.

When it comes to getting media from dokuwiki, this time for both images and pdf, I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dokuwiki.py", line 337, in get
    data = b64decode(data)
  File "/usr/lib/python2.7/base64.py", line 73, in b64decode
    return binascii.a2b_base64(s)
TypeError: must be string or buffer, not instance
```

There is a similar report [here](https://github.com/splitbrain/dokuwiki/issues/1087) for perl, so maybe there's a similar [solution](https://www.dokuwiki.org/devel:xmlrpc?do=diff&rev2%5B0%5D=1425779419&rev2%5B1%5D=1427714333&difftype=sidebyside) for python. 

Thanks, Dennis

**Comment by fmenabe** [comment]
Hi Dennis,

There was a bug in the 'get' and 'set' methods. base64 encoding/decoding was indeed done manually instead of using the 'Binary' object of the xmlrpclib/xmlrpc.client module.

But 'add' method was already using the 'Binary' object and should have worked.

Dokuwiki really seems sensitive about the type of the files! I had a file which had not the good extension (png extension for a pnm file) and it was rejected (I had to convert it to a png file).

I push a commit in an 'issue7' branch that should correct the bug (tested with python 2.7 and 3.5). Can you confirm it works?

François

**Comment by laaber** [comment]
Hi François,

thanks for your reply.
I tried the old version again and you're right: the 'add' method works fine. I'm sorry I messed things up a little.

I also tested the new version and now it works fine, so I can confirm for python 2.7. :)
Thank you!

Dennis

**Comment by fmenabe** [comment]
I release the new version on Pypi.

Thanks for reporting the bug!
